language: php
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

## Build matrix for lowest and highest possible targets
matrix:
  include:

    - php: 7.0
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=lowest
    - php: 7.0
      env: dependencies=highest
    - php: 7.1
      env: dependencies=highest
    - php: 7.2
      env: dependencies=highest

install:
  - composer install

script:
  - vendor/bin/phpunit